"""initial migration

Revision ID: 001
Revises:
Create Date: 2026-07-17 23:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("source_type", sa.String(20), nullable=False),
        sa.Column("source_url", sa.String(2048), nullable=False),
        sa.Column("title", sa.String(500), nullable=False, server_default=""),
        sa.Column("duration_seconds", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("transcript_json", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="processing"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "practice_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("material_id", sa.String(36), nullable=False),
        sa.Column("mode", sa.String(30), nullable=False, server_default="sentence_by_sentence"),
        sa.Column("status", sa.String(20), nullable=False, server_default="in_progress"),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("pronunciation_score", sa.Float(), nullable=True),
        sa.Column("rhythm_score", sa.Float(), nullable=True),
        sa.Column("intonation_score", sa.Float(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_practice_sessions_material_id"), "practice_sessions", ["material_id"])
    op.create_table(
        "sentence_attempts",
        sa.Column("id", postgresql.UUID(as_uuid=False), nullable=False),
        sa.Column("session_id", sa.String(36), nullable=False),
        sa.Column("sentence_index", sa.Integer(), nullable=False),
        sa.Column("audio_recording_url", sa.String(2048), nullable=False, server_default=""),
        sa.Column("reference_audio_url", sa.String(2048), nullable=False, server_default=""),
        sa.Column("score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("word_scores_json", postgresql.JSONB(), nullable=True),
        sa.Column("waveform_data_json", postgresql.JSONB(), nullable=True),
        sa.Column("suggestions_json", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sentence_attempts_session_id"), "sentence_attempts", ["session_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sentence_attempts_session_id"), table_name="sentence_attempts")
    op.drop_table("sentence_attempts")
    op.drop_index(op.f("ix_practice_sessions_material_id"), table_name="practice_sessions")
    op.drop_table("practice_sessions")
    op.drop_table("materials")
    # ### end Alembic commands ###
